apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudsentinel-config
  namespace: cloudsentinel
data:
  NODE_ENV: "production"
  PROMETHEUS_URL: "http://prometheus-service:9090"
  GRAFANA_URL: "http://grafana-service:3000"
  REDIS_URL: "redis://redis-service:6379"
  NEXT_TELEMETRY_DISABLED: "1"
