global:
  resolve_timeout: 5m

route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 12h
  receiver: 'cloudsentinel-webhook'
  routes:
    - match:
        severity: critical
      receiver: 'cloudsentinel-webhook'
      continue: true
    - match:
        severity: warning
      receiver: 'cloudsentinel-webhook'

receivers:
  - name: 'cloudsentinel-webhook'
    webhook_configs:
      - url: 'http://cloudsentinel:3000/api/alerts'
        send_resolved: true
