apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudsentinel-config
  namespace: cloudsentinel
data:
  PROMETHEUS_URL: "http://prometheus-service:9090"
  GRAFANA_URL: "http://grafana-service:3001"
  NODE_ENV: "production"
