apiVersion: v1
kind: Secret
metadata:
  name: cloudsentinel-secrets
  namespace: cloudsentinel
type: Opaque
stringData:
  POSTGRES_PASSWORD: "sentinel123"
  REDIS_PASSWORD: ""
  GRAFANA_ADMIN_PASSWORD: "admin123"
